aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout
      - run:
          name: Install Hugo
          command: apt-get update && apt-get install hugo
      - run:
          name: Build the project
          command: hugo
      - run:
          name: Deploy to Surge.sh
          command: |
            echo "Deploying to Surge.sh..."
            export PATH="$PATH:$(yarn global bin)"
            yarn global add surge
            surge --project public/ --domain blog.rakinu.com
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master
