aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  build-deploy-blog:
    docker:
      - image: cibuilds/hugo:latest
    environment:
      HUGO_BUILD_DIR: ./public

    steps:
      - run:
          name: Install dependencies
          command: apk update && apk add --update yarn git
      - checkout
      - run:
          name: Install submodules
          command: git submodule sync && git submodule update --init
      - run:
          name: Build the project
          command: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run:
          name: Deploy to Surge.sh
          command: |
            export PATH="$PATH:$(yarn global bin)"
            yarn global add surge
            surge --project $HUGO_BUILD_DIR --domain blog.rakinu.com
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-deploy-blog:
          filters: *filter-only-master
